name: Run tests

on: [push, pull_request]

jobs:
  build-n-publish:
    name: Run tests
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python: [3.5, 3.7, 3.8]
    steps:
    - uses: actions/checkout@master
    - name: Set up Python
      uses: actions/setup-python@v2.2.1
      with:
        python-version: ${{ matrix.python }}
    - name: Run tests
      run: |
        pip3 install tox flake8
        make deps
        make all
